class ErrorCodes:
    # 400 Bad Request
    BAD_REQUEST = "BAD_REQUEST"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    INVALID_QUERY_PARAM = "INVALID_QUERY_PARAM"

    # 401 Unauthorized
    UNAUTHORIZED = "UNAUTHORIZED"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"

    # 403 Forbidden
    FORBIDDEN = "FORBIDDEN"

    # 404 Not Found
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    USER_NOT_FOUND = "USER_NOT_FOUND"

    # 409 Conflict
    DUPLICATE_RESOURCE = "DUPLICATE_RESOURCE"
    STATE_CONFLICT = "STATE_CONFLICT"

    # 422 Unprocessable Entity
    UNPROCESSABLE_ENTITY = "UNPROCESSABLE_ENTITY"

    # 429 Too Many Requests
    TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS"

    # 500
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    DATABASE_ERROR = "DATABASE_ERROR"
    UNKNOWN_ERROR = "UNKNOWN_ERROR"
