import os
import sys
import random
from decimal import Decimal
from datetime import datetime, timedelta

from werkzeug.security import generate_password_hash

CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(CURRENT_DIR)
if PROJECT_ROOT not in sys.path:
    sys.path.append(PROJECT_ROOT)

from src.app import create_app  # noqa: E402
from src.app.extensions import db  # noqa: E402
from src.app.models import (  # noqa: E402
    User,
    Author,
    Category,
    Book,
    Order,
    OrderItem,
    Review,
)

CATEGORY_DEFINITIONS = [
    ("Fiction", "fiction"),
    ("Essays", "essays"),
    ("Self Improvement", "self-improvement"),
    ("IT & Programming", "it-programming"),
    ("Business", "business"),
    ("Science", "science"),
    ("History", "history"),
    ("Travel", "travel"),
]

AUTHOR_FIRST_NAMES = [
    "Avery",
    "Blair",
    "Casey",
    "Dakota",
    "Emery",
    "Finley",
    "Gray",
    "Hayden",
    "Indigo",
    "Jules",
]

AUTHOR_LAST_NAMES = [
    "Reeves",
    "Bennett",
    "Hawkins",
    "Hughes",
    "Kelley",
    "Morgan",
    "Parker",
    "Sheridan",
    "Wells",
    "Young",
]

BOOK_TITLES = [
    "Designing APIs",
    "Stories from the Road",
    "Thinking in Systems",
    "Modern Web Backends",
    "Habits that Stick",
    "Structuring Your Data",
    "Shipping Great Products",
    "Exploring New Places",
    "Historical Perspectives",
    "Science Experiments",
]

PUBLISHERS = [
    "Northwind House",
    "Pinecone Press",
    "Signal & Noise",
    "Magellan Publishing",
]

REVIEW_TEMPLATES = [
    "Learned a lot from this book.",
    "A quick and practical read.",
    "Would recommend it to a friend.",
    "The pacing was great throughout.",
    "Solid reference material.",
]


def clear_and_create_tables():
    print("[*] Dropping all tables...")
    db.drop_all()
    print("[*] Creating all tables...")
    db.create_all()
    print("[*] DB schema recreated.")


def seed_users():
    print("[*] Seeding users...")
    users = []

    admin = User(
        email="admin@example.com",
        name="Admin",
        role="ADMIN",
        password_hash=generate_password_hash("Admin123!"),
    )
    users.append(admin)

    for i in range(1, 10):
        user = User(
            email=f"user{i}@example.com",
            name=f"User{i}",
            role="USER",
            password_hash=generate_password_hash(f"User{i}123!"),
        )
        users.append(user)

    db.session.add_all(users)
    db.session.commit()

    print(f"[*] Inserted {len(users)} users.")
    return users


def seed_categories():
    print("[*] Seeding categories...")

    categories = [
        Category(name=name, slug=slug) for name, slug in CATEGORY_DEFINITIONS
    ]

    db.session.add_all(categories)
    db.session.commit()

    print(f"[*] Inserted {len(categories)} categories.")
    return categories


def seed_authors():
    print("[*] Seeding authors...")
    authors = []

    for _ in range(20):
        full_name = f"{random.choice(AUTHOR_FIRST_NAMES)} {random.choice(AUTHOR_LAST_NAMES)}"
        authors.append(
            Author(
                name=full_name,
                bio=f"{full_name} is a prolific writer in our demo catalog.",
            )
        )

    db.session.add_all(authors)
    db.session.commit()

    print(f"[*] Inserted {len(authors)} authors.")
    return authors


def generate_isbn13(existing_codes):
    while True:
        digits = "978" + "".join(str(random.randint(0, 9)) for _ in range(10))
        if digits not in existing_codes:
            existing_codes.add(digits)
            return digits


def seed_books(authors, categories):
    print("[*] Seeding books...")
    books = []
    isbn_pool = set()

    for i in range(80):
        title = f"{random.choice(BOOK_TITLES)} #{i + 1}"
        author = random.choice(authors)
        category = random.choice(categories)
        price = Decimal(random.randint(8, 35) * 1000)

        book = Book(
            title=title,
            description=f"{title} is part of the autogenerated demo catalog.",
            price=price,
            stock_cnt=random.randint(0, 50),
            isbn13=generate_isbn13(isbn_pool),
            publisher=random.choice(PUBLISHERS),
            published_at=datetime.utcnow().date() - timedelta(days=random.randint(0, 365 * 3)),
            author_id=author.id,
            category_id=category.id,
        )
        books.append(book)

    db.session.add_all(books)
    db.session.commit()

    print(f"[*] Inserted {len(books)} books.")
    return books


def seed_orders_and_reviews(users, books):
    print("[*] Seeding orders & reviews...")

    orders = []
    order_items = []
    reviews = []

    target_users = [u for u in users if u.role == "USER"]

    for user in target_users:
        for _ in range(random.randint(2, 4)):
            created_at = datetime.utcnow() - timedelta(days=random.randint(0, 60))
            order = Order(
                user_id=user.id,
                status=random.choice(["PENDING", "PAID", "SHIPPED", "COMPLETED"]),
                total_amount=Decimal("0"),
                created_at=created_at,
            )
            db.session.add(order)
            db.session.flush()

            num_items = random.randint(1, 4)
            picked_books = random.sample(books, num_items)

            order_total = Decimal("0")
            for book in picked_books:
                quantity = random.randint(1, 3)
                item = OrderItem(
                    order_id=order.id,
                    book_id=book.id,
                    quantity=quantity,
                    unit_price=book.price,
                )
                db.session.add(item)
                order_items.append(item)
                order_total += book.price * quantity

                if random.random() < 0.5:
                    review = Review(
                        user_id=user.id,
                        book_id=book.id,
                        rating=random.randint(3, 5),
                        content=random.choice(REVIEW_TEMPLATES),
                        created_at=created_at + timedelta(hours=random.randint(1, 72)),
                    )
                    db.session.add(review)
                    reviews.append(review)

            order.total_amount = order_total
            orders.append(order)

    db.session.commit()

    print(f"[*] Inserted {len(orders)} orders.")
    print(f"[*] Inserted {len(order_items)} order_items.")
    print(f"[*] Inserted {len(reviews)} reviews.")

    return orders, order_items, reviews


def main():
    app = create_app("dev")

    with app.app_context():
        clear_and_create_tables()

        users = seed_users()
        categories = seed_categories()
        authors = seed_authors()
        books = seed_books(authors, categories)
        seed_orders_and_reviews(users, books)

        total_rows = (
            User.query.count()
            + Author.query.count()
            + Category.query.count()
            + Book.query.count()
            + Order.query.count()
            + OrderItem.query.count()
            + Review.query.count()
        )
        print(f"[*] Total logical rows (with duplicates) ~ {total_rows}")


if __name__ == "__main__":
    main()
